[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64

[Output]
Format=uki
Output=mkosi-lab
OutputDirectory=mkosi.output

[Build]
CacheDirectory=mkosi.cache

[Content]
Packages=systemd
         udev
         linux-image-amd64
         python3
         kmod
         dbus
         login
         apt
         iproute2
         iputils-ping
         net-tools
         bind9-dnsutils
         traceroute
         tcpdump
         ethtool
         curl
         ca-certificates
         openssh-server
         systemd-resolved
         sudo
         systemd-boot-efi
RootPassword=lab
RootShell=/bin/bash
KernelCommandLine=console=ttyS0
