Vagrant.configure("2") do |config|
  config.vm.define "apt-cacher-ng" do |m|
    m.vm.box      = "debian/bookworm64"
    m.vm.hostname = "apt-cacher-ng"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.ssh.insert_key = false

    m.vm.network "private_network",
      ip:                    "192.168.200.2",
      libvirt__network_name: "mkosi-lab",
      libvirt__host_ip:      "192.168.200.1",
      libvirt__dhcp_start:   "192.168.200.10",
      libvirt__dhcp_stop:    "192.168.200.254"

    m.vm.provider :libvirt do |lv|
      lv.cpus   = 1
      lv.memory = 512
    end

    # Install apt-cacher-ng (runs once on first provision)
    m.vm.provision "shell", inline: <<~SHELL
      apt-get update -qq
      DEBIAN_FRONTEND=noninteractive apt-get install -y apt-cacher-ng curl
      sed -i 's/^#\?.*BindAddress:.*/BindAddress: 0.0.0.0/' /etc/apt-cacher-ng/acng.conf
      sed -i 's/^#\?.*PassThroughPattern:.*/PassThroughPattern: .*/' /etc/apt-cacher-ng/acng.conf
      systemctl enable --now apt-cacher-ng
    SHELL
  end
end
